relay_pin: 14 # in BCM numbering
set_point: 95 # in degrees C
delay_time: 5 # in seconds
plot_interval: 2 # in hours
db_path: /home/pi/piggia/temps.db
max_entries: 10000 # max entries in DB
K_p: 3
K_i: 0.02
K_d: 200
